import React from 'react';

export const metadata = {
  title: 'about page',
  description: 'Generated by create next app',
}

const page = () => {
  return (
    <div className='container'>
      
    </div>
  );
};

export default page;